import React from 'react';
import { formatINR } from '../data/payslipData';

export default function PayslipDetails({ details, netPay }) {
  if (!details) return null;

  return (
    <div className="bg-white dark:bg-slate-900 border border-slate-100 dark:border-slate-800/80 rounded-2xl p-5 shadow-2xs">
      <h3 className="text-sm font-bold text-slate-900 dark:text-white mb-4">
        Payslip Details
      </h3>

      <div className="space-y-3 text-xs divide-y divide-slate-100 dark:divide-slate-800/60">
        <div className="flex items-center justify-between pt-1">
          <span className="text-slate-500 dark:text-slate-400">Month</span>
          <span className="font-bold text-slate-900 dark:text-white">
            {details.month}
          </span>
        </div>

        <div className="flex items-center justify-between pt-2.5">
          <span className="text-slate-500 dark:text-slate-400">Pay Period</span>
          <span className="font-medium text-slate-800 dark:text-slate-200">
            {details.payPeriod}
          </span>
        </div>

        <div className="flex items-center justify-between pt-2.5">
          <span className="text-slate-500 dark:text-slate-400">Pay Date</span>
          <span className="font-medium text-slate-800 dark:text-slate-200">
            {details.payDate}
          </span>
        </div>

        <div className="flex items-center justify-between pt-2.5">
          <span className="text-slate-500 dark:text-slate-400">Net Pay</span>
          <span className="font-extrabold text-emerald-600 dark:text-emerald-400">
            {formatINR(netPay)}
          </span>
        </div>

        <div className="flex items-center justify-between pt-2.5">
          <span className="text-slate-500 dark:text-slate-400">Status</span>
          <span className="inline-flex items-center px-2 py-0.5 rounded-full text-[11px] font-bold bg-emerald-50 dark:bg-emerald-950/60 text-emerald-600 dark:text-emerald-400 border border-emerald-100 dark:border-emerald-800/60">
            {details.status || 'Paid'}
          </span>
        </div>

        <div className="flex items-center justify-between pt-2.5">
          <span className="text-slate-500 dark:text-slate-400">Generated On</span>
          <span className="font-medium text-slate-800 dark:text-slate-200">
            {details.generatedOn}
          </span>
        </div>

        <div className="flex items-center justify-between pt-2.5">
          <span className="text-slate-500 dark:text-slate-400">Generated By</span>
          <span className="font-medium text-slate-800 dark:text-slate-200">
            {details.generatedBy}
          </span>
        </div>
      </div>
    </div>
  );
}
